### ISSUE TITLE
[epic] Roadmap

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-libp2p#777]
epic issue to follow every "big" projects planned. It's loosely sorted by priority from different teams

- [ ] https://github.com/status-im/nim-libp2p/issues/698
- [ ] Simulations & tests to improve gossipsub performances & reliability (via testground)
- [ ] Hole punching
- [ ] https://github.com/status-im/nim-libp2p/issues/358
- [ ] Better interoperability tests ([libp2p/test-plans](https://github.com/libp2p/test-plans/))
- [ ] Running as C library
- [ ] https://github.com/status-im/nim-libp2p/pull/725
- [ ] Async exception tracking
- [ ] Pluggable GossipSub scoring
- [ ] kad-dht
- [ ] https://github.com/status-im/nim-libp2p/issues/409
- [ ] https://github.com/status-im/nim-libp2p/pull/611
- [ ] Optimize: bandwidth, memory, latency, cpu
- [ ] Improve existing APIs (protobuf, multiaddress, builder)
- [ ] Bluetooth Transport
